.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MYSQL-SNMP 1 "July 17, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mysql-snmp \- MySQL-Server SNMP agent for Net-SNMP
.SH SYNOPSIS
.B mysql-snmp
.RI "[ options ]"
.SH DESCRIPTION
.B mysql-snmp
is a Net-SNMP (snmpd) agent that can be used to monitor a MySQL server with SNMP. 
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
display help
.TP
.B \-v, \-\-verbose
be verbose about what you do

.TP
.B \-V, \-\-version
output version information and exit

.TP
.B \-\-daemon-pid=FILE
write PID to FILE instead of /var/run/mysql-snmp.pid

.TP
.B \-u DBUSER
use DBUSER as user to connect to mysql

.TP
.B \-p DBPASS
use DBPASS as password to connect to mysql

.TP
.B \-h, \-\-host HOST
connect to mysql server HOST

.TP
.B \-P, \-\-port PORT
port to connect (default 3306)

.TP
.B \-c|\-\-config FILE
read MySQL configuration from FILE

.TP
.B \-m,\-\-master
adds SNMP counters for masters

.TP
.B \-s,\-\-slave
adds SNMP counters for slaves

.TP
.B \-b,\-\-heartbeat DB.TABLE 
compute slave lag with the maatkit mk-heartbeat stamp table.

.TP
.B \-\-oid OID
anchor the MIB to this root OID

.TP
.B \-i,\-\-refresh
refresh interval in seconds

.SH MYSQL CONFIGURATION
You can specify the mysql connection parameters in a config file using 
my.cnf format, like this:

.sp
.RS 3n
.nf
[client]
host=dbserver
port=3306
user=monitor
password=secret
.fi
.RE

.SH SEE ALSO
.BR snmpcmd (1).
.br
.SH AUTHOR
mysql-snmp was written by Brice Figureau
.PP
This manual page was written by Brice Figureau <brice@daysofwonder.com>,
for the Debian project (but may be used by others).
